<?
    $caj->cajasAbiertas();
    $caj->aperturarCaja();
    
?>
<div id='mensaje_error'><? echo $caj->mensaje."<a href=index.php?opt=caja&menu=detallecaja&id=1&fecha=".$caj->row[1].">".date("d/m/Y",strtotime($caj->row[1]))."</a>";?></div>
<div id='espacioblanco'></div>
<!-- <form>
<table>
    <tr>
	<td>
            <input type="text" value="<?=date("d/m/Y");?>" readonly name="theDate">
            <input type="button" value="Calendario" onclick="displayCalendar(document.forms[0].theDate,'dd/mm/yyyy',this)">
            <input type="submit" value="Aperturar">
        </td>
    </tr>
</table>
</form>--->
<div id="debug"></div>