<?
require('controller/caja.class.php');
$caj =  new Caja();
?>
<div id='submenu'>
    <a href='index.php?opt=caja&menu=aperturacaja'>APERTURA</a>
    <a href='index.php?opt=caja&menu=cierrecaja'>CERRAR</a>
    <a href='index.php?opt=caja&menu=detallecaja'>MOVIMIENTOS</a>
    <a href='index.php?opt=caja&menu=resumencaja'>RESUMEN</a>
</div>
<div id='espacioblanco'></div>
<?
if(isset($_GET['menu'])){
    $menu = $_GET['menu'];
}else{
    $menu = 'resumencaja';
}
if(is_file("view/".$menu.".phtml")){
    require_once("view/".$menu.".phtml");
}else{
    require_once("view/error.phtml");
}
?>