<? $caj->listarCaja(); ?>
<table>
    <thead>
        <tr>
            <th width="50px">CODIGO</th><th width="80px">FECHA</th><th width="120px">INGRESOS</th>
            <th width="120px">EGRESOS</th><th width="120px">SALDO</th><th width="20px">E</th><th width="20px">O</th>
        </tr>
    </thead>
    <tbody>
<?
foreach ($caj->resultado as $resulta) {
    echo '<tr>';
    echo '<td align="center">'.$resulta['id_caja'].'</td><td align="center">'.date("d/m/Y",strtotime($resulta['fecha_caja_cab'])).'</td>
    <td align="right">'.$resulta['montoin_caja_cab'].'</td><td align="right">'.$resulta['montofin_caja_cab'].'</td>
    <td align="right">'.$resulta['saldo'].'</td>';
    if($resulta['estado_caja_cab']==1){
        echo'<td align="center"><img src="image/closed.png" title="CERRADO" width="16px"></td>
            <td align="center"><a href="index.php?opt='.$opt.'&menu=detallecaja&id='.$resulta['id_caja'].'&fecha='.date("d/m/Y",strtotime($resulta['fecha_caja_cab'])).'">
            <img src="image/b_confirm.png" title="VISUALIZAR" width="16px"></a></td>';
    }else{
        echo'<td align="center"><img src="image/open.png" title="ABIERTO" width="16px"></td>
            <td align="center"><img src="image/add.png" title="MODIFICAR" width="16px"></td>';
    }
    echo '</tr>';
    $dia1 = date("d/m/Y");
    $dia2 = date("d/m/Y",strtotime($resulta['fecha_caja_cab']));
    if ($dia2 == $dia1){
        echo $dia1.' hola ';
    }else{
        echo $resulta['fecha_caja_cab'];
    }
}
?>
</tbody>
</table>